// Generated by CoffeeScript 1.6.2
/*!
* Magicio 0.1
*
* Copyright 2013, Brad Fults - http://bradfults.com/
* Released under the MIT License
* https://github.com/h3h/magicio/LICENSE
*
* Thanks to Dave Rupert for Lettering.js
* https://github.com/davatron5000/Lettering.js
*/


(function() {
  (function($) {
    var log, methods, settings;

    settings = {};
    log = function(msg) {
      if (settings.debug) {
        return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
      }
    };
    methods = {
      init: function(options) {
        settings = {
          requireActionOnBreak: false,
          debug: false
        };
        settings = $.extend(settings, options);
        return this.each(function() {
          log("Initializing magicio for element with id \"" + this.id + "\"");
          return $(this).lettering('words').data('magicio', {
            thing: 'bob'
          });
        });
      },
      run: function() {
        return this.each(function() {
          return log($(this).data('magicio'));
        });
      }
    };
    return $.fn.extend({
      magicio: function(method) {
        if (methods[method]) {
          return methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
        } else {
          return methods.init.apply(this, arguments);
        }
      }
    });
  })(jQuery);

}).call(this);
